#ifndef M03GT1DJVVY5ATIA5EVKBG6RQY_SOFTWARE_SHADER_API_H
# define M03GT1DJVVY5ATIA5EVKBG6RQY_SOFTWARE_SHADER_API_H

# include "software_shader.h"

#endif // M03GT1DJVVY5ATIA5EVKBG6RQY_SOFTWARE_SHADER_API_H
